### ISSUE TITLE
[BUG] Can't register without using Google Play Services on Android

### ISSUE THREAD

**Issue by MegaArthur** [mapswipe/mapswipe#120]
The new update introduced a fatal bug -- android devices without Google Play Services can't log in or register due to the app using firebase for registering (WHY?).

Log:

```

09-30 22:00:22.465 E/RNFirebaseAuth(22703): createUserWithEmailAndPassword:onComplete:failure
09-30 22:00:22.465 E/RNFirebaseAuth(22703): com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.

```

**Comment by laurentS** [comment]
Hi @MegaArthur ! Thanks for your feedback! And sorry that the update broke the app for you.

I'm very confused by your report, because mapswipe has used firebase (for auth, but also for all backend functions) since the very beginning, so I don't understand why this is happening now.

Could you share some more details about your phone config? What OS are you using? Have you patched it with anything like [microG](https://microg.org/) or equivalent? Were you able to use all functions of the app before yesterday's update?

**Comment by MegaArthur** [comment]
I am using Havoc OS Pie (9.0.0).

It's rooted, so I can debug some more if you want me to.

I do not use anything like MicroG, so I guess that's why "FIREBASE_AUTH_API" is unavailable.

Before the update the app worked good.

**Comment by laurentS** [comment]
Hi @MegaArthur 
I looked a bit further into this, and my understanding is that the old version used the web version of firebase, but we've now switched to the mobile "enhanced" version, mostly because it offers much better offline support, which is something many users have requested for a long time (and didn't really work before). #64 can tell you more about this.
I think this native version is what is causing you problems, though I can't reproduce the problem so it's hard to confirm.
We don't have enough resources at the moment to deal with both issues, so we'll have to prioritize offline, given how many people have requested it. If you're interested in helping out, you can always send a PR :) (but please note this would probably not be an easy fix)

**Comment by Rudloff** [comment]
I also can't login anymore since I updated.
I am using  Android 7.1.2 without Play Services.

**Comment by MegaArthur** [comment]
Hmm, I seem to be able to log-in now, not sure what changed though. What about you, @Rudloff ?

**Comment by Rudloff** [comment]
I tried 2.0.1 and I still can't login.

And I still get the same error in the logs:
```
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: signInWithEmailAndPassword:onComplete:failure
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at com.google.firebase.FirebaseExceptionMapper.getException(Unknown Source)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at com.google.android.gms.common.api.internal.zag.zaa(Unknown Source)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(Unknown Source)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(Unknown Source)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.connect(Unknown Source)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(Unknown Source)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(Unknown Source)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at android.os.Handler.dispatchMessage(Handler.java:98)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at android.os.Looper.loop(Looper.java:154)
11-13 20:00:00.315 11068 11068 E RNFirebaseAuth: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by MegaArthur** [comment]
Oh, disregard my previous comment, I was using an old backup of the app and didn't notice how old it was, it was from before the update

**Comment by qeef** [comment]
I am not running Google Services neither microG. Would it be able to run mapswipe in such a configuration? Maybe in the future?

As the mapswipe is opensource, will it be available at F-Droid?

Why is not the OAuth to osm used instead of whatever?

I am sorry for these -- maybe silly -- questions. I am curious about reasons & decisions, however.

**Comment by Rudloff** [comment]
> As the mapswipe is opensource, will it be available at F-Droid?

See https://github.com/mapswipe/mapswipe/issues/1.
This app can not be published on F-Droid because it uses non-free libraries.

**Comment by laurentS** [comment]
@qeef Thanks for the questions, they are far from silly.
- about f-droid, @Rudloff is right, unless we move away from using google firebase, we can't release the app there..
- Using OAuth via osm has a ticket already #35 we've just not worked on it yet, because we prioritised other features first. And even if we moved to logins using osm, the rest of the app heavily relies on firebase for loading data and so on, so you would probably be able to login, but not use anything past that.

While I would personally love to get rid of all things google, there are a few reasons for using firebase:
- historically, the app was initially built on it, because it meant not having to build a backend server, or worry about scaling. This is still the case. To move away, we would need to build a backend API server that serves the projects and tasks. While not necessarily very difficult, it would require a lot more resources than we have at the moment, for building it, and then maintaining the server(s).
- when we rebuilt the app for v2, we talked about this, but the same concerns still apply. The move from the app-side toolkit to the one we now use was essentially mandated by the need for the app to work better offline (the old version didn't really work from this point of view).

Given the API compatibility of both app-side toolkits (I think), it may be possible to go back to the original toolkit, but we'd need to look into how much work that requires, both for keeping the current functionality, and also to support offline properly. This might allow running on a phone like yours, while not needing a big backend change
The difficulty being in balancing how many more users we'd get from that change, vs the effort needed.

@qeef just to clarify, did the old version of the app work for you, without any google services or microG?

**Comment by qeef** [comment]
>     * historically, the app was initially built on it, because it meant not having to build a backend server, or worry about scaling. This is still the case. To move away, we would need to build a backend API server that serves the projects and tasks. While not necessarily very difficult, it would require a lot more resources than we have at the moment, for building it, and then maintaining the server(s).

I am always sorry to hear things like this. Some great open source project comes but inventors don't care much about scalability, performance, architecture, overall design, and so. Then the project becomes unreliable, hard to maintain or extend, and with performance issues. The same story for HOT Tasking Manager, IMHO.

> The difficulty being in balancing how many more users we'd get from that change, vs the effort needed.

I do not think it's worth the effort in terms of the number of users.

> @qeef just to clarify, did the old version of the app work for you, without any google services or microG?

In old days I had an Android with Google services, so there was no problem. Now, I use Android without Google services and it doesn't work. Maybe, I will try the microG yet, that could be the solution.

**Comment by MegaArthur** [comment]
@laurentS

Seen as the old version of the app worked for me withou microG, can I still use it to contribute?

Will my swipes be saved if I still use the old version?

**Comment by laurentS** [comment]
@MegaArthur sadly, not really. For a variety of reasons, we had to change the data format in the backend, so the old and new app are not compatible. We have also removed everything from the old backend now, as virtually all users have upgraded their app. So you would be able to open the old app and login, but nothing else.
This really bothers me. I'll have a chat with the rest of the team to see what options we have.

**Comment by laurentS** [comment]
Almost a year has passed... This weekend I've actually been able to login with the app on a phone using /e/ (which is based on lineageOS) with microG 0.2.13. It looks like [this commit](https://github.com/microg/android_packages_apps_GmsCore/commit/c3bfb63f27c116d21ba7b2b87629e36573d4a59e) made it possible.

**Comment by NotSoImportant** [comment]
Using lineageos without gapps i am unable to login with 2.0.8.
did not try any older version.
