### ISSUE TITLE
Wrong tasks in group results

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe#619]
**Describe the bug**
it seems that the app writes a results to a group which the task doesn't belong to. The last 4 tasks should belong to another group.

```
{
  "endTime" : "2022-03-02T05:39:06.870Z",
  "results" : {
    "t16798" : 1,
    "t16799" : 1,
    "t16800" : 1,
    "t16801" : 1,
    "t16802" : 1,
    "t16803" : 1,
    "t16804" : 1,
    "t16805" : 1,
    "t16806" : 1,
    "t16807" : 1,
    "t16808" : 1,
    "t16809" : 1,
    "t16810" : 1,
    "t16811" : 1,
    "t16812" : 1,
    "t16813" : 1,
    "t16814" : 1,
    "t16815" : 1,
    "t16816" : 1,
    "t16817" : 1,
    "t16818" : 1,
    "t16819" : 1,
    "t16820" : 1,
    "t16821" : 1,
    "t16822" : 1,
    "t16823" : 1,
    "t16824" : 1,
    "t16825" : 1,
    "t16826" : 1,
    "t16827" : 1,
    "t16828" : 1,
    "t16829" : 1,
    "t16830" : 1,
    "t16831" : 1,
    "t16832" : 1,
    "t16833" : 1,
    "t16834" : 1,
    "t17427" : 1,
    "t17428" : 1,
    "t17429" : 1,
    "t17430" : 1
  },
  "startTime" : "2022-03-02T05:38:57.185Z"
}
```

**App version**
not really clear, but probably 2.1.8

**Time of crash**
2022-03-02T05:38:57.185Z

**To Reproduce**
can't reproduce

userID: `ej8YSzSA4yS2WOPpTebnVP02GDX2`

**Additional context**
I've noticed this because it triggered an error in the backend workers when transfering the results to postgres.

```
DETAIL:  Key (project_id, group_id, task_id)=(-Mx0_479a3w9FD9oMv5o, g554, t17427) is not present in table "tasks".
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mapswipe_workers/firebase_to_postgres/transfer_results.py", line 93, in transfer_results_for_project
    save_results_to_postgres(results_file)
  File "/usr/local/lib/python3.8/dist-packages/mapswipe_workers/firebase_to_postgres/transfer_results.py", line 292, in save_results_to_postgres
    p_con.query(query_insert_results)
  File "/usr/local/lib/python3.8/dist-packages/mapswipe_workers/auth.py", line 64, in query
    self._db_cur.execute(query, data)
psycopg2.errors.ForeignKeyViolation: insert or update on table "results" violates foreign key constraint "results_project_id_fkey2"
DETAIL:  Key (project_id, group_id, task_id)=(-Mx0_479a3w9FD9oMv5o, g554, t17427) is not present in table "tasks".
```

**Comment by laurentS** [comment]
Not sure what the cause for this is, but if we don't see it happening again within a few days, we can probably assume it was related to some edge case (like a crash in an outdated app or something similar)

**Comment by Hagellach37** [comment]
it happened again:

```
{
  "XmZqEgx1k6Py7aMs82nV607bDoZ2" : {
    "endTime" : "2022-03-10T19:32:47.046Z",
    "results" : {
      "t13875" : 1,
      "t13876" : 1,
      "t13877" : 1,
      "t13878" : 1,
      "t13879" : 1,
      "t13880" : 1,
      "t13881" : 1,
      "t13882" : 1,
      "t13883" : 1,
      "t13884" : 1,
      "t13885" : 1,
      "t13886" : 1,
      "t13887" : 1,
      "t13888" : 1,
      "t13889" : 1,
      "t13890" : 1,
      "t13891" : 1,
      "t13892" : 1,
      "t13893" : 1,
      "t13894" : 1,
      "t13895" : 1,
      "t13896" : 1,
      "t13897" : 1,
      "t13898" : 1,
      "t13899" : 1,
      "t13900" : 1,
      "t13901" : 1,
      "t13902" : 1,
      "t13903" : 1,
      "t13904" : 1,
      "t13905" : 1,
      "t13906" : 1,
      "t13907" : 1,
      "t13908" : 1,
      "t13909" : 1,
      "t13910" : 1,
      "t13911" : 1,
      "t14467" : 1,
      "t14468" : 1
    },
    "startTime" : "2022-03-10T19:32:38.655Z"
  }
}
```

**Comment by Hagellach37** [comment]
as a work aroung I'm manually deleting the additional results in firebase. The backend can then transfer the results.

Ideally we could add checks to both parts client and backend.

**Comment by laurentS** [comment]
Proposed solution for now:
- check the ids of results vs ids of tasks we received
- if anything does not match, remove extraneous results, log an error in Sentry for further analysis
- upload corrected results to backend
